name = "YeoJohnson"
uuid = "4236c574-1900-44e3-aa41-0fcb6fed4f9a"
authors = ["Patrick Moehrke"]
version = "0.1.0"

[deps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
